### ISSUE TITLE
Lobby slots size did not update after `!mp settings`

### ISSUE THREAD

**Issue by Kotoki1337** [hburn7/Brigitta#38]
![image](https://user-images.githubusercontent.com/35394151/215418954-a7c8b14a-3753-4245-bcc6-72ee6a662243.png)

**Comment by hburn7** [comment]
!mp settings "Players: 0" means there are 0 players in lobby, the size is still assumed to be 16 until !mp set or !mp size is used. And in some cases, it doesn't work properly yet. Thanks for letting me know though!

**Comment by hburn7** [comment]
Feel free to follow this issue https://github.com/hburn7/BanchoSharp/issues/34
