### ISSUE TITLE
Chat log will be empty if `Display times in UTC+0` is enable

### ISSUE THREAD

**Issue by Kotoki1337** [hburn7/Brigitta#39]
Encode issues? Everything will be fine if this setting disabled on my PC

![image](https://user-images.githubusercontent.com/35394151/215422222-9fb438d7-90c1-4ff3-8375-d3d8ec1f82a0.png)

**Comment by hburn7** [comment]
Confirmed reproduced

**Comment by hburn7** [comment]
Fixed in v2.0.5
