### ISSUE TITLE
[Feature Request] Play a sound whenever a match starts/finishes

### ISSUE THREAD

**Issue by Sclafus** [hburn7/Brigitta#58]
Hello! First of all, nice project!
I have a feature request that would improve the experience quite a bit:
Whenever a match starts or finishes, a notification is displayed in the bottom left corner of the screen. That is fine, but adding a sound for the notification would improve drastically the experience since you can focus on other windows until you hear the notification.
Ideally, after the match starts, a sound notification should be sent if somebody types a message (probably someone asking to abort)
What do you think about it?

**Comment by hburn7** [comment]
Thanks for the request! Sound cues like this are definitely something I want to implement in the future. It will probably take a few months before I have the time, but I'm sure they will come in the future.

**Comment by Sclafus** [comment]
I may do a PR then, is it ok?

**Comment by hburn7** [comment]
I will be working on this myself soon.

**Comment by hburn7** [comment]
Added in v2.4.0

**Comment by Sclafus** [comment]
Thank you so much! I will try it soon, hopefully
For future reference: related PR #69 (nice)
