### ISSUE TITLE
Match Tab showing as Unread when focused on that chat

### ISSUE THREAD

**Issue by TimperNL** [hburn7/Brigitta#65]
When you are focused on the match tab, and you receive a message from a PLAYER, the tab gets colored as unread.
This does not happen when you receive messages from BanchoBot.
Added a video of it happening:
https://www.youtube.com/watch?v=uIvQ3g4j5fY

**Comment by hburn7** [comment]
Should be fixed as of v2.4.0, please let me know @TimperNL

**Comment by TimperNL** [comment]
Yeah, I've not seen it happen anymore, looks to be fixed!
Thank you
